#!/bin/bash
# Phylogenomic Tree Reconstruction using IQ-TREE

# Create output directory
mkdir -p iqtree_out

# Run IQ-TREE using the core alignment generated by snippy-core
# -s: Input alignment file
# -m: Substitution model selection (MFP = ModelFinder Plus finds the best-fit model)
# -bb: Ultrafast bootstrap replicates (1000 is standard for statistical support)
# -nt: Number of CPU threads (AUTO lets IQ-TREE optimize core usage)
iqtree -s snippy_out/core_alignment/core.aln \
       -m MFP \
       -bb 1000 \
       -nt AUTO \
       --prefix iqtree_out/phylogeny

echo "Phylogenetic analysis complete. Tree files saved to iqtree_out/"
