#!/bin/bash
# Pan-genome Analysis using Panaroo

# Create output directory
mkdir -p panaroo_out

# Run Panaroo using your GFF files generated by Prokka
# --clean-mode: 'strict' removes contamination and poorly aligned draft fragments
# -a: Sequence alignment type (core creates a core genome alignment)
# --aligner: Sequence aligner tool (mafft is standard)
panaroo -i annotation/*.gff \
        -o panaroo_out \
        --clean-mode strict \
        -a core \
        --aligner mafft \
        -t 4

echo "Pan-genome analysis complete. Results saved to panaroo_out/"
